export default function Constants() {
    const skills = {
    "Accounting" : 5,
    "Anthropology" : 1,
    "Appraise" : 5,
    "Archaeology" : 1,
    "Charm" : 5,
    "Climb" : 20,
    "Credit Rating" : 0,
    "Cthulhu Mythos" : 0,
    "Disguise" : 0,
    "Dodge" : "Half Dex",
    "Drive Auto" : 20,
    "Elec. Repair" : 10,
    "Fast Talk" : 5,
    "Fighting(Brawl)" : 25,
    "Firearms(Handgun)" : 20,
    "Firearms(Rifle)" : 25,
    "First Aid" : 30,
    "History" : 5,
    "Intimidate" : 15,
    "Jump" : 20,
    "Law" : 5,
    "Library Use" : 20,
    "Listen" : 20,
    "Locksmith" : 1,
    "Mech. Repair" : 10,
    "Medicine" : 1,
    "Natural World" : 10,
    "Navigate" : 10,
    "Occult" : 5,
    "Persuade" : 10,
    "Psychoanalysis" : 1,
    "Psychology" : 10,
    "Ride" : 5,
    "Sleight of Hand" : 10,
    "Spot Hidden" : 25,
    "Stealth" : 20,
    "Swim" : 20,
    "Throw" : 20,
    "Track" : 10
    }
}
