
export const skills = [
    {name: "Accounting",
     score: 5},
    {name: "Anthropology",
    score: 1},
    {name: "Appraise",
     score: 5},
    {name: "Archaeology",
    score: 1},
    {name: "Charm",
     score: 5},
    {name: "Climb",
    score: 20},
    {name: "Credit Rating",
     score: 0},
    {name: "Cthulhu Mythos",
    score: 0},
    {name: "Disguise",
     score: 5},
    {name: "Dodge",
    score: 1},
    {name: "Drive Auto",
     score: 20},
    {name: "Elec. Repair",
    score: 10},
    {name: "Fast Talk",
     score: 5},
    {name: "Fighting(Brawl)",
    score: 25},
    {name: "Firearms(Handgun)",
     score: 20},
    {name: "Firearms(Rifle)",
    score: 25},
    {name: "First Aid",
     score: 30},
    {name: "History",
    score: 5},
    {name: "Intimidate",
     score: 15},
    {name: "Jump",
    score: 20},
    {name: "Law",
     score: 5},
    {name: "Library Use",
    score: 20},
    {name: "Listen",
     score: 20},
    {name: "Locksmith",
    score: 1},
    {name: "Mech Repair",
     score: 10},
    {name: "Medicine",
    score: 1},
    {name: "Natural World",
     score: 10},
    {name: "Navigate",
    score: 10},
    {name: "Occult",
     score: 5},
    {name: "Persuade",
    score: 10},
    {name: "Psychoanalysis",
     score: 1},
    {name: "Psychology",
    score: 10},
    {name: "Ride",
     score: 5},
    {name: "Sleight of Hand",
    score: 10},
    {name: "Spot Hidden",
     score: 25},
    {name: "Stealth",
    score: 20},
    {name: "Swim",
     score: 20},
    {name: "Throw",
    score: 20},
    {name: "Track",
     score: 10},               
]

export const professionalSkills = [40,40,40,50,50,50,60,60,70]

export const personalSkills = [20,20,20,20]
